import assert from 'node:assert/strict';
import {readReview,reviewKey,matchesRegisterView,registerEntryKind,registerEntryCounts,registerEntrySummary,registerReviewStatus} from '../assets/js/task-register.mjs';
assert.deepEqual(readReview(null),{version:1,records:{}});
assert.throws(()=>readReview('{"version":2,"records":{}}'));
assert.throws(()=>readReview('{"version":1,"records":{"vet:2026:a":{"completed":"yes","reviewedOn":"2026-09-17"}}}'));
const item={id:'annual-duty',year:'2026',reviewComplete:false,schedule:{kind:'date',endDate:'2026-03-01'}};
assert.notEqual(reviewKey('vet',item,2026),reviewKey('vet',item,2027));
assert.notEqual(reviewKey('vet',item,2026),reviewKey('tas',item,2026));
assert.notEqual(reviewKey('tas',{id:'weekly-scan-0',recordKey:'weekly-scan-0::2026-09-14'},2026),reviewKey('tas',{id:'weekly-scan-0',recordKey:'weekly-scan-0::2026-09-21'},2026));
assert.equal(matchesRegisterView(item,'past','2026-09-17'),true);
assert.equal(matchesRegisterView({...item,reviewComplete:true},'past','2026-09-17'),false);
assert.equal(matchesRegisterView({...item,schedule:{kind:'trigger'}},'trigger','2026-09-17'),true);
assert.equal(matchesRegisterView({...item,schedule:{kind:'date',endDate:'2026-12-01'}},'later','2026-09-17'),true);
assert.equal(matchesRegisterView({...item,schedule:{kind:'window',startDate:'2027-02-01',endDate:'2027-02-05'}},'past','2026-09-17'),false);
assert.equal(matchesRegisterView({...item,procedureOnly:true},'past','2026-09-17'),false);
const mixed=[item,{...item,id:'week-1',entryKind:'scheduled'},{...item,id:'week-2',entryKind:'scheduled'},{...item,id:'event',entryKind:'event'},{...item,id:'guide',entryKind:'event',procedureOnly:true}];
assert.deepEqual(registerEntryCounts(mixed),{core:1,scheduled:2,procedure:1,event:1});
assert.equal(registerEntrySummary(mixed),'1 core duty · 2 scheduled occurrences · 1 procedure guide · 1 saved event');
assert.equal(registerEntryKind({entryKind:'unknown'}),'core');
assert.equal(matchesRegisterView(mixed[4],'event','2026-09-17'),false);
assert.equal(matchesRegisterView(mixed[4],'reference','2026-09-17'),true);
assert.equal(matchesRegisterView(mixed[1],'scheduled','2026-09-17'),true);
// Native VET labels and TAS status codes share the same review indicator.
for(const [status,expected] of [['Waiting','Waiting'],['In progress','In progress'],['in-progress','In progress'],['exception','Exception'],['Performed','Performed'],['recorded','Recorded']])assert.equal(registerReviewStatus({...item,status}),expected);
for(const status of ['not-started','Not started','not-reviewed','unavailable','completed','verified','not-applicable','unknown'])assert.equal(registerReviewStatus({...item,status}),'');
for(const guard of [{reviewComplete:true},{complete:true},{procedureOnly:true},{historyOnly:true},{statusAppliesToYear:false},{progressAvailable:false}])assert.equal(registerReviewStatus({...item,status:'waiting',...guard}), '');
assert.equal(registerReviewStatus({...item,status:'waiting',year:'2026',statusAppliesToYear:true}),'Waiting');
console.log('PASS full-register filtering, year separation and invalid review recovery');
